import TanstackQueryProvider from "@/components/tanstack-query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import { inter } from "@/lib/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <TanstackQueryProvider>
          <SessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              {children}
              <Footer />

              <Toaster
                //
                richColors
                expand
                closeButton
              />
            </ThemeProvider>
          </SessionProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
